---
server:
  addr: 0.0.0.0:9090
  request_timeout: 3 # second
  response_timeout: 120 # second, for pprof change it to 120

log:
  level: "debug"

redis:
  network: tcp
  addr: 127.0.0.1:6379
  database: 0
  dial_timeout: 5
  read_timeout: 5
  write_timeout: 5
  pool_size: 5
  pool_timeout: 10
  min_idle_conns: 5
  max_retries: 3
